Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Afghanistan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Albania','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Algeria','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Angola','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Argentina','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Armenia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Aruba','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Australia','Australia Dollar','AUD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Austria','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Azerbaijan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bahamas','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bahrain','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bangladesh','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Barbados','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Belarus','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Belgium','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Belize','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bermuda','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bhutan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bolivia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bosnia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Botswana','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Brazil','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Brunei','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Bulgaria','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Burundi','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Cambodia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Canada','Canada Dollar','CAD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Cape Verde','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Cayman Islands','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('CFA Franc BCEAO','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('CFA Franc BEAC','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('CFP Franc','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Chili','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('China','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Colombia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Comoros','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Congo','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Costa Rica','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Croatia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Cuba','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Cuba Convertible','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Cyprus','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Czech','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Denmark','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Djibouti','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Dominican Republich','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('East Caribbean','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Egypt','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('El Salvador','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Estonia','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Ethiopia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Europe','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Falkland Islands','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Fiji','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Finland','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('France','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Gambia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Georgia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Germany','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Ghana','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Gibraltar','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Great Britain','Great Britain Pound','GBP'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Greece','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Guatemala','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Guinea','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Guyana','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Haiti','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Honduras','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Hong Kong','Hong Kong Dollar','HKD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Hungary Forint','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Iceland','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Indonesia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Iran','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Iraq','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Ireland','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Israel','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Italy','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Jamaica','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Japan','Japan Yen','JPY'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Jordan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Kazakhstan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Kenya','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Kuwait','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Kyrgyzstan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Laos','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Latvia','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Lebanon','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Lesotho','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Liberia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Libya','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Lithuania','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Luxembourg','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Macau','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Macedonia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Malagasy','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Malawi','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Malaysia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Maldives','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Malta','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Mauritania','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Mauritius','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Mexico','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Moldova','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Mongolia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Morocco','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Mozambique','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Myanmar','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Namibia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Nepal','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Netherlands','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('New Zealand','New Zealand Dollar','NZD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Nicaragua Cordoba','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Nigeria','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('NL Antilles','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('North Korea','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Norway','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Oman','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Pakistan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Panama','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Papua New Guinea','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Paraguay','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Peru Nuevo','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Philippines','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Poland','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Portugal','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Qatar','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Romania','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Russia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Rwanda','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Samoa','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Sao Tome/Principe','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Saudi Arabia','Saudi Arabia Riyal','SAR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Serbia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Seychelles','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Sierra Leone','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Singapore','Singapore Dollar','SGD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Slovakia','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Slovenia','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Solomon Islands','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Somali Shilling','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('South Africa','South Africa Rand','ZAR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('South Korea','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Spain','Euro','EUR'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Sri Lanka','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('St Helena','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Sudan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Suriname','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Swaziland','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Sweden','Sweden Krona','SEK'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Switzerland','Switzerland Franc','CHF'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Syria','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Taiwan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Tanzania','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Thailand','Thailand Baht','THB'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Tonga','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Trinidad/Tobago','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Tunisia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Turkey','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Turkmenistan','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Uganda','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Ukraine','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('United Arab Emirates','United Arab Emirates Dirham','AED'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Uruguay','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('USA','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Vanuatu','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Venezuela','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Vietnam','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Yemen','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Zambia','US Dollar','USD'); 
Insert into tbl_country_cur(`country_name`, `currency_name`, `currency_code`)values ('Zimbabwe','US Dollar','USD');  